version: '3.5'

networks:
  default:
  traefik:
    name: swarm_traefik
    external: true

volumes:
  wordpress_mariadb_data:
    external: true

configs:
  nginx_vhost_php:
    file: ../configs/nginx/wordpress-swarm.conf
  wordpress_config:
    file: ../configs/wordpress/wp-config-swarm.php

services:
  nginx:
    hostname: nginx
    image: phpughh/wordpress-nginx:6.0.3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"

        - "traefik.http.services.wordpress-svc.loadbalancer.server.port=80"
        - "traefik.http.routers.wordpress.entrypoints=http"
        - "traefik.http.routers.wordpress.rule=HostRegexp(`wordpress-php{phpversion:[0-9]+}.phpug.hh`,`localhost`)"
        - "traefik.http.routers.wordpress.service=wordpress-svc"
        - "traefik.http.routers.wordpress.middlewares=x-requestid@file,access-log@file"
    networks:
      - default
      - traefik
    configs:
      - source: nginx_vhost_php
        target: /etc/nginx/conf.d/default.conf
        mode: 0644
    healthcheck:
      test: netstat -ltn | grep -q -c ":80" || exit 1
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3

  php:
    hostname: php
    image: phpughh/wordpress-php:6.0.3
    networks:
      - default
    configs:
      - source: wordpress_config
        target: /var/www/html/wp-config.php
        mode: 0644
    healthcheck:
      test: netstat -ltn | grep -q -c ":9000" || exit 1
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3