api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"
    forwardedHeaders:
      insecure: true
  mariadb:
    address: ":3306"

log:
  level: "ERROR"

providers:
  kubernetesCRD: {}
  file:
    filename: /traefik-config/dynamic.yml

experimental:
  localPlugins:
    x-requestid:
      moduleName: git.toniliesche.de/tliesche/traefik-x-requestid
    access-log:
      moduleName: git.toniliesche.de/tliesche/traefik-access-log