apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: wordpress-ingressroute

spec:
  entryPoints:
    - http
  routes:
    - match: Host(`wordpress.phpug.hh`)
      kind: Rule
      middlewares:
        - name: access-log@file
        - name: x-requestid@file
      services:
      - name: wordpress-service
        kind: Service
        port: 80