version: '3.5'

networks:
  default:
    name: phpughh
    external: true

volumes:
  wordpress_mariadb_data:
    external: true

configs:
  nginx_vhost:
    file: ../configs/nginx/wordpress-simple.conf

services:
  mariadb:
    hostname: mariadb
    image: phpughh/mariadb:10.9
    volumes:
      - wordpress_mariadb_data:/var/lib/mysql
    networks:
      - default
    environment:
      - MYSQL_ROOT_PASSWORD=phpughh
    ports:
      - "3306:3306"
    healthcheck:
      test: netstat -ltn | grep -q -c ":3306" || exit 1
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3

  nginx:
    hostname: nginx
    image: nginx:1.23-alpine
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ~/phpughh/wordpress:/var/www/html/wordpress
    networks:
      - default
    configs:
      - source: nginx_vhost
        target: /etc/nginx/conf.d/default.conf
        mode: 0644
    healthcheck:
      test: netstat -ltn | grep -q -c ":80" || exit 1
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3

  php:
    hostname: php
    image: phpughh/php-fpm:${PHP_VERSION}
    depends_on:
      - mariadb
    volumes:
      - ~/phpughh/wordpress:/var/www/html/wordpress
    networks:
      - default
    healthcheck:
      test: netstat -ltn | grep -q -c ":9000" || exit 1
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3