version: '3.5'

networks:
  default:
    name: phpughh
    external: true

configs:
  nginx_vhost:
    file: ../configs/nginx/hello-world.conf

services:
  nginx:
    hostname: nginx
    image: nginx:1.23-alpine
    depends_on:
      - php
    volumes:
      - ~/phpughh/hello_world:/var/www/html/hello_world
    networks:
      - default
    configs:
      - source: nginx_vhost
        target: /etc/nginx/conf.d/default.conf
        mode: 0644
    labels:
      - "traefik.enable=true"

      - "traefik.http.services.nginx-svc.loadbalancer.server.port=80"
      - "traefik.http.routers.nginx.entrypoints=http"
      - "traefik.http.routers.nginx.rule=HostRegexp(`helloworld.phpug.hh`)"
      - "traefik.http.routers.nginx.service=nginx-svc"

  php:
    hostname: php
    image: php:8.1-fpm-alpine
    depends_on:
      - mariadb
    volumes:
      - ~/phpughh/hello_world:/var/www/html/hello_world
    networks:
      - default