version: '3.5'

services:
  php:
    build:
      context: ../images/php-fpm
      args:
        php_version: 7.4
    image: phpughh/php-fpm:7.4

  php-dev:
    build:
      context: ../images/php-fpm-dev
      args:
        php_version: 7.4
    image: phpughh/php-fpm:7.4-dev