version: '3.5'

networks:
  default:
    name: phpughh
  traefik:
    name: phpughh_traefik

volumes:
  wordpress_mariadb_data:
    external: true

configs:
  nginx_vhost_php7.4:
    file: ../configs/nginx/wordpress-php7.4.conf
  nginx_vhost_php8.1:
    file: ../configs/nginx/wordpress-php8.1.conf

services:
  mariadb:
    hostname: mariadb
    image: phpughh/mariadb:10.9
    volumes:
      - wordpress_mariadb_data:/var/lib/mysql
    networks:
      - default
      - traefik
    environment:
      - MYSQL_ROOT_PASSWORD=phpughh
    healthcheck:
      test: netstat -ltn | grep -q -c ":3306" || exit 1
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3
    labels:
      - "traefik.enable=true"

      - "traefik.tcp.services.mariadb-svc.loadbalancer.server.port=3306"
      - "traefik.tcp.routers.mariadb.service=mariadb-svc"
      - "traefik.tcp.routers.mariadb.entrypoints=mariadb"
      - "traefik.tcp.routers.mariadb.rule=HostSNI(`*`)"

  nginx:
    hostname: nginx
    image: nginx:1.23-alpine
    depends_on:
      - php
    volumes:
      - ../apps/wordpress:/var/www/html/wordpress
    networks:
      - default
      - traefik
    configs:
      - source: nginx_vhost_php7.4
        target: /etc/nginx/conf.d/php74.conf
        mode: 0644
      - source: nginx_vhost_php8.1
        target: /etc/nginx/conf.d/default.conf
        mode: 0644
    labels:
      - "traefik.enable=true"

      - "traefik.http.services.nginx-svc.loadbalancer.server.port=80"
      - "traefik.http.routers.nginx.entrypoints=http"
      - "traefik.http.routers.nginx.rule=HostRegexp(`wordpress-php{phpversion:[0-9]+}.phpug.hh`,`localhost`)"
      - "traefik.http.routers.nginx.service=nginx-svc"

  php74:
    hostname: php-74
    image: phpughh/php-fpm:7.4
    depends_on:
      - mariadb
    volumes:
      - ../apps/wordpress:/var/www/html/wordpress
    networks:
      - default

  php81:
    hostname: php-81
    image: phpughh/php-fpm:8.1
    depends_on:
      - mariadb
    volumes:
      - ../apps/wordpress:/var/www/html/wordpress
    networks:
      - default