version: '3.5'

networks:
  default:
    name: phpughh

volumes:
  wordpress_mariadb_data:
    external: true

configs:
  nginx_vhost:
    file: ../configs/wordpress-simple.conf

services:
  mariadb:
    hostname: mariadb
    image: mariadb:10.9-jammy
    volumes:
      - wordpress_mariadb_data:/var/lib/mysql
    networks:
      - default
    environment:
      - MYSQL_ROOT_PASSWORD=phpughh
    healthcheck:
      test: netstat -ltn | grep -q -c ":3306" || exit 1
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3
    ports:
      - "3306:3306"

  nginx:
    hostname: nginx
    image: nginx:1.23-alpine
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ../apps/wordpress:/var/www/html/wordpress
    networks:
      - default
    configs:
      - source: nginx_vhost
        target: /etc/nginx/conf.d/default.conf
        mode: 0644

  php:
    hostname: php
    image: php:8.1-fpm-alpine
    depends_on:
      - mariadb
    volumes:
      - ../apps/wordpress:/var/www/html/wordpress
    networks:
      - default