kind: Service
apiVersion: v1
metadata:
  name: mariadb-service
spec:
  type: LoadBalancer
  ports:
    - name: rdbms
      targetPort: rdbms
      protocol: TCP
      port: 3306
  selector:
    app: mariadb
