kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
spec:
  type: LoadBalancer
  ports:
    - name: web
      targetPort: web
      port: 80
    - name: rdbms
      targetPort: rdbms
      port: 3306
  selector:
    app: traefik
